{
  pkgs,
  lib,
  config,
  ...
}:
{

  sops.secrets."traefik/env" = {
    sopsFile = ../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."traefik" = {
    image = "traefik:v3.2.1";
    environmentFiles = [
      "/run/secrets-for-users/traefik/env"
    ];
    volumes = [
      "/data/docker/traefik/letsencrypt:/letsencrypt:rw"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      # "80:80/tcp"
      "443:443/tcp"
    ];
    # When updating this also update ../../services/nix_cache_server.nix
    cmd = [
      "--accesslog=true"
      "--accesslog.filePath=/logs/access.log"
      "--api.insecure=true"
      "--providers.docker=true"
      "--providers.docker.exposedbydefault=false"

      "--entryPoints.http.address=:80"
      "--entrypoints.web.http.redirections.entrypoint.to=https"
      "--entryPoints.web.http.redirections.entrypoint.scheme=https"

      "--entryPoints.https.address=:443"
      "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      "--certificatesresolvers.cloudflare.acme.email=jarneamerlinck@pm.me"
      "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
    ];

    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.traefik-dash.entrypoints" = "https";
      "traefik.http.routers.traefik-dash.rule" = "Host(`${config.networking.hostName}.ko0.net`)";
      "traefik.http.routers.traefik-dash.service" = "traefik-dash";
      "traefik.http.routers.traefik-dash.tls" = "true";
      "traefik.http.routers.traefik-dash.tls.certresolver" = "cloudflare";
      "traefik.http.services.traefik-dash.loadbalancer.server.port" = "8080";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=traefik"
      "--network=frontend"
    ];
  };
  systemd.services."docker-traefik" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "docker-network-frontend.service"
    ];
    requires = [
      "docker-network-frontend.service"
    ];
    partOf = [
      "docker-compose-traefik-root.target"
    ];
    wantedBy = [
      "docker-compose-traefik-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-frontend" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f frontend";
    };
    script = ''
      docker network inspect frontend || docker network create frontend
    '';
    partOf = [ "docker-compose-traefik-root.target" ];
    wantedBy = [ "docker-compose-traefik-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-traefik-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
