kubernetes:
    cloudflare-api-token.yaml: ENC[AES256_GCM,data:lnxZmcQOXxEbx/SxH0bnBIL7Yv3uO73O1+Qr6VXLS36vVfT8XhXHiLDl7y37GGNwTcOtJyma4R35Tc5VPP55mqOLkBuDXl0cW2FsdLWZtadz2kJJH1S3FhkgS7IejNwzLmu0fJAe75RKKBguu5WjAGBw+anc4GW6xsqwpMXrlE5SHOe9kYSHGWWCjcf0/UbhAdCbj0kWiBXd8ZLUFuVolS/BWkWEoYOMlilfE9UTGM5Q6eAAXlc=,iv:Aql2LjP0myijX/xN8btvBPsa8kLqsxEpOx1Wql+Op8c=,tag:OcVx+AhuERg45p8g48Mg+w==,type:str]
sops:
    age:
        - recipient: age1683w3al5uvzfg4jn6jzmuwtcxjq0vrmlhzs8k90khta5ahcuvpvqg6fqky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnd1MU4rRVlpZ1orYldM
            Z1dzTEJXYitqMzFYVE9OZTQ3Z0xLTGxqTkFZCnk0SjA5VUR2bmRDQUxST2c4Mm9I
            TEhaU1VVZUt0eHBtQkdQaFVWWmtxNE0KLS0tIFJBSEd6MW5QS1FhQU50Rys1SVFC
            dGdrd1RXZjg2a2RzWm4yRDBWLzlpclEKKsCYgaj9pTgWaHk53SdKfiG7bUTtcew+
            7jUqjTm9ZrapfPkjvEVN6HzUeNxORdlQMaOFdZKy5uZqk0xuyFHMBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v9eu0t6crm766jn22nj5n473t646w5c09dwja5et9fpy3xe7cfzqgjuykw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbm4yM05LNFFCSkhIUlRq
            Sk8yNGY4NnpKZUJHREZJVmM0RFVUTCtzZ3hvCm5aSzNmb2ZnMzd5VC9CV3BMK0h3
            S0pKcmlCdUpwSjVXbDF1ZVNhOFVWakEKLS0tIDRLV2VNMkpWNnBLUzFxeld2QkVF
            WU1XNVV4K3p5dSs0NnQzRElvbHBINlkKvXBSp+CI8SzkP2ibEm1bDZ+khIEUBB9B
            3crtCfNaGnuwMYTft8e8Qq5oUEo1XIBcXcsJZ5apC3jvPti9sdP8iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-25T20:13:30Z"
    mac: ENC[AES256_GCM,data:Xte1D1KYblvSwBJRutrvTwKcxyshp7DKJ3lGSRVrU3x07o1CgzOTIg+KCATDdzxyEWEbFlIvIQ6OmRVNtQCHR/RL6KgVye+iwz/8szOzrNGnzXrYSPP/OrMy+tfMVE7y24gLUnBGYQnwojaLUmpuVFcGVagM3Py6FGR3iZdknRQ=,iv:TLDDWkWxQoZuHoUzz3F239GNXanTnyK0CG5PuSjMgtI=,tag:xd1OB4ZdZ++ebdmE1atpkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
