kubernetes:
    cloudflare-api-token.yaml: ENC[AES256_GCM,data:PDBsXcEB2yXtG0DZYzcUrh/k8B8OTHxvvQ6FfLIe9LzhnXLRQ8bd0EN+PzJdiK5O5sbjkRHMIT13cDFlHmim5gSvYdhtRwJanBRovza9nKIiIJRDOxco14htYmXU5bi55V3FC0XgjiITITfgYzHQrY3Rq/euKtYzl2I3f+EHr9EpfGtpdeLim8alRpgnemApLjMr54QK24Z/cu2c1vhHbvEZakKQk4EJukU1/KMTTUw4L7mmlzo=,iv:drP6YSoeb1hI/oevrL1VEp2FW/gtii31osePvx0Zp4A=,tag:LAzzTaBKraNHbKf5pIg2gw==,type:str]
sops:
    age:
        - recipient: age1683w3al5uvzfg4jn6jzmuwtcxjq0vrmlhzs8k90khta5ahcuvpvqg6fqky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJjV01VR3VrMmtpQUNT
            Y3ZySXNyWC83VTJUNDkvcVRBdWVWTWM2N1YwClNxRkRETjdubXFmNS9xQk1hQ21K
            aDliVGVYZFBqZkNucGdZQStOME5QZm8KLS0tIHZuSVFhMmo2bWNlWjFnTVFWcDBE
            WEdrdExWU2dkMFRORzhJMGpMTWRZYWcKHkZ+gCua45qCfl23GOXPtzcPyA8nVMGa
            wecbzNcHcIPigN2+ZAitco08I6U6fHigrIC4jXuRSimi5d0PrjNSRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v9eu0t6crm766jn22nj5n473t646w5c09dwja5et9fpy3xe7cfzqgjuykw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOCtzMUNqUjhuUDk4WHB5
            K25OSW5SS084WUZvN0g1TGNHM3VnMmxRcno4ClcrbGlSZzcvczVpQnBnR01IWlRn
            eXczYkNMc1N2NzZrUTFzem1saXROcWMKLS0tIDJrOFUxbGEwQzVQaG5PWkN6aUtU
            MWFDcjhxQk1TL2pXUWNhNktCNVJHLzAK97oQYGPGvhTW6Z9i9DSADBF39ncHUZsG
            BSmmRmEUVnFD5jdLvxM1cweLcOxPYa2vOyqL66KbPFE2p6ioncjzSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T17:44:59Z"
    mac: ENC[AES256_GCM,data:UrzSmZqBwNrBe7wO6A9k3lOZMxwMnc+RNbc+INSpgkdCrHGGsZ6338htxJDw7q2sfEf8o71MyS5ROqENqwPCzWlgd9UpMFtjXft9nh7m4YObERWdmXKL5NW/janaCt6uHYnVfrm0qHIsDCzHw5F9VUDvPE5Lbt1Q8cEBQf+E0MM=,iv:TMjPtcS56cIwA0DdJqNjMAfFCdtdQfTrKkjpoSBIFgY=,tag:rVcgl50/EKnawSmABdj7Zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
