kubernetes:
    cloudflare-api-token.yaml: ENC[AES256_GCM,data:1mkfaiE+7GZ+u/94RXQiKKm5HIJWuUmyiRKJT3Yxm3UzLgYSaCKt5HPQDDFSoxSFlxQ0mKgwnW2a8nU7S55pKFP4p1SdiFit4/rvarI8ep7jWJGUJcF5in5uiMZFtgU+HUInkImRWkdfU+UD4BmwXniUYHWzfVWX056XiH6JTQrXECZzdL7KBTazFBf8zekcZTwsORk5n7hT1hGF/a8ykI3zg3IykanFEZToGFaCh9eV4vsT+zY=,iv:uvXkU0seZIy1Aqpqn3GufGIJZnA9xfAJHB3Qojv5FOs=,tag:snZLAzmvMqSUJexDQ27bvw==,type:str]
sops:
    age:
        - recipient: age1683w3al5uvzfg4jn6jzmuwtcxjq0vrmlhzs8k90khta5ahcuvpvqg6fqky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWHhmNVN6WksxOUFha0RQ
            YnY5OEdlQlBaalFvMUFXaWRFQll0VmxzUVN3CmZycHhaRzhOVjlJSzF6RFBKV1Iv
            OU9veWh4a1IyQW5MZUgzL2x6aE9Lck0KLS0tIEdLejFsaHlKRldtQmJrbWtGU0tI
            dmtxZDd1LzNISTJSUC9YbE1GMW9rZncKBjnGDDdw0ESCtrjSMzO8nlptdiXGyZl3
            ALz8RdVlAJQlxvfhztRsJ1iUW8VxLMHacoRwnz2ECGgvzR5nBJJ2Qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v9eu0t6crm766jn22nj5n473t646w5c09dwja5et9fpy3xe7cfzqgjuykw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXpoK2I0TGtjb0ZjcVdH
            MW0zTDk5RGFydmJZMGhoVVdXYnlZcGZDdEZNCkJYMFFjYXM1anVDdUVOdndlc0U5
            WURCeEQ0RFIvRjcvZXNZZmZROW1FVGMKLS0tIGpoUlRIZndtR2N4SzNmdzhhaVdj
            OEpwOTIrWEhnTEE0K3BJbUtuWUVmancKjfT9PIcoqbQHcCBiGvFxz4fFPbDLzk6i
            emPhordHzrZ/NZTKscNXR1Vi7vPUyC7GBbwfHx5TTEpHbYEg6OLKGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T12:58:28Z"
    mac: ENC[AES256_GCM,data:YaCvlUN4EwT1VnVqzdY3PlT8EYK9bFd7Tp3JlnlAYm30K4O11n1CKWBL1INq1budCUo/VMY+z1GNOP0PY6+qziOo25hRyQtfO+M86eIMW+CMOEI5FpqZR7O+7nikIniaQ6VZvMcn1lHpO//mm2d6GhmnV39QDZwgN7Hi0elfxU4=,iv:DhSz47fqFzOPJ/C/b1JAjUsenSq+etgFS5piNM0YFLI=,tag:E0eDwGTfdXm/gcLImMlulQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
