kubernetes:
    cloudflare-api-token.yaml: ENC[AES256_GCM,data:SkOrlv3QPoMf+vsC30lnv9c0Ov1NAJPvxTvHoWpVPXCwtirXWF4DYpChAXazhZ2k/tg4nbjka1MBzxImYjM7ULbs9VOmdR7KVfpxS5CMKvep92yZV9mGpSsIuN4PC6Gpgpb2lrIhRmLbgbuzWkQRlDzu/tEvyn/1kKswI3kqBY7PLvdgpJLFNRze/oDPbGxcOWWdJJFO/+PYob1rkhTwUsDoehNfMlIaU8krRBWkjInRnvzQWr4=,iv:n9+P+evZyIUuFiS5EzTZp0W+DQlp+J9QrhXGtS3m/pQ=,tag:yrmZnRgnNnn2dktdrWOcaw==,type:str]
sops:
    age:
        - recipient: age1683w3al5uvzfg4jn6jzmuwtcxjq0vrmlhzs8k90khta5ahcuvpvqg6fqky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnd1MU4rRVlpZ1orYldM
            Z1dzTEJXYitqMzFYVE9OZTQ3Z0xLTGxqTkFZCnk0SjA5VUR2bmRDQUxST2c4Mm9I
            TEhaU1VVZUt0eHBtQkdQaFVWWmtxNE0KLS0tIFJBSEd6MW5QS1FhQU50Rys1SVFC
            dGdrd1RXZjg2a2RzWm4yRDBWLzlpclEKKsCYgaj9pTgWaHk53SdKfiG7bUTtcew+
            7jUqjTm9ZrapfPkjvEVN6HzUeNxORdlQMaOFdZKy5uZqk0xuyFHMBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v9eu0t6crm766jn22nj5n473t646w5c09dwja5et9fpy3xe7cfzqgjuykw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbm4yM05LNFFCSkhIUlRq
            Sk8yNGY4NnpKZUJHREZJVmM0RFVUTCtzZ3hvCm5aSzNmb2ZnMzd5VC9CV3BMK0h3
            S0pKcmlCdUpwSjVXbDF1ZVNhOFVWakEKLS0tIDRLV2VNMkpWNnBLUzFxeld2QkVF
            WU1XNVV4K3p5dSs0NnQzRElvbHBINlkKvXBSp+CI8SzkP2ibEm1bDZ+khIEUBB9B
            3crtCfNaGnuwMYTft8e8Qq5oUEo1XIBcXcsJZ5apC3jvPti9sdP8iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T16:03:42Z"
    mac: ENC[AES256_GCM,data:Ppl91/Ohttv+9IKGJPQmVPANkpd3y2tf9clqyLGkji3z4dxpyEJdEKjDOmyBv/5dvG86npP1ELBIq2daEtAVkWoJ5GGuU8Tx2smR+g0f1EQcoF0KTem4dbiSzKdwLo31Q0yN7vTAmLUJt02Adajbvizj4cFOcQ6yGrpGTsfsJ84=,iv:Usjv/hjd5IIre0SPvMilB10yLwdIcMN5K++QYtT7V/s=,tag:J9/zMpEfSOTzOc/mSBEKeQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
