# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.oci-containers.containers."homebox-homebox" = {
    image = "ghcr.io/hay-kot/homebox:v0.10.3";
    environment = {
      "HBOX_LOG_FORMAT" = "text";
      "HBOX_LOG_LEVEL" = "info";
      "HBOX_OPTIONS_ALLOW_REGISTRATION" = "false";
      "HBOX_WEB_MAX_UPLOAD_SIZE" = "10";
    };
    volumes = [
      "/data/docker/homebox:/data:rw"
    ];
    ports = [
      "3100:7745/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homebox"
      "--network=homebox_caddy_net"
    ];
  };
  systemd.services."docker-homebox-homebox" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-homebox_caddy_net.service"
    ];
    requires = [
      "docker-network-homebox_caddy_net.service"
    ];
    partOf = [
      "docker-compose-homebox-root.target"
    ];
    wantedBy = [
      "docker-compose-homebox-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-homebox_caddy_net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homebox_caddy_net";
    };
    script = ''
      docker network inspect homebox_caddy_net || docker network create homebox_caddy_net
    '';
    partOf = [ "docker-compose-homebox-root.target" ];
    wantedBy = [ "docker-compose-homebox-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homebox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
