exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows


## If like to embrace black styles even in the docs:
- repo: https://github.com/asottile/blacken-docs
  rev: 1.20.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

# - repo: https://github.com/Yelp/detect-secrets
#   rev: v1.5.0
#   hooks:
#     - id: detect-secrets
#       exclude: |
#         (^|/)secrets.ya?ml$

# - repo: local
#   hooks:
#     - id: nix-flake-check
#       name: Nix Flake Check
#       entry: nix flake check
#       language: system
#       types: [nix]

- repo: https://github.com/astro/deadnix
  rev: v1.3.1
  hooks:
    - id: deadnix
      args: [--edit] # Uncomment to automatically modify files
      stages: [pre-commit]

- repo: https://github.com/NixOS/nixfmt
  rev: v1.0.1
  hooks:
    - id: nixfmt-nix
