# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  # Containers
  virtualisation.oci-containers.containers."freshrss" = {
    image = "lscr.io/linuxserver/freshrss:1.24.3-ls244";
    environment = {
      "PGID" = "100";
      "PUID" = "1442";
      "TZ" = "Europe/London";
    };
    volumes = [
      "/data/docker/freshrss:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=freshrss"
      "--network=frontend"
      "--network=rss"
    ];
  };
  systemd.services."docker-freshrss" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-frontend.service"
      "docker-network-rss.service"
    ];
    requires = [
      "docker-network-frontend.service"
      "docker-network-rss.service"
    ];
    partOf = [
      "docker-compose-rss-root.target"
    ];
    wantedBy = [
      "docker-compose-rss-root.target"
    ];
  };
  virtualisation.oci-containers.containers."full-test-rss" = {
    image = "heussd/fivefilters-full-text-rss:3.8.1";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=full-test-rss"
      "--network=rss"
    ];
  };
  systemd.services."docker-full-test-rss" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-rss.service"
    ];
    requires = [
      "docker-network-rss.service"
    ];
    partOf = [
      "docker-compose-rss-root.target"
    ];
    wantedBy = [
      "docker-compose-rss-root.target"
    ];
  };

  systemd.services."docker-network-rss" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f rss";
    };
    script = ''
      docker network inspect rss || docker network create rss
    '';
    partOf = [ "docker-compose-rss-root.target" ];
    wantedBy = [ "docker-compose-rss-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-rss-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
