# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];
  boot = {
    loader.grub = {
      efiSupport = true;
      efiInstallAsRemovable = true;
    };
    initrd = {
      availableKernelModules = [
        "btrfs" # Needed for btrfs storage
        "ahci" # Used for SATA (Advanced Host Controller Interface)
        "xhci_pci" # Controller for USB (eXtensible Host Controller Interface)
        "usbhid" # Needed for USB devices
        "usb_storage" # For USB storage devices
        "virtio_pci" # PCI for virtio, only needed if VM is needed
        "virtio_blk" # Block for virtio, only needed if VM is needed
        "sr_mod" # Used for CD-ROM
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };
  hardware.sensor.iio.enable = true;

  swapDevices = [ ];
  services.fwupd.enable = true;

  disko.devices.disk.boot_disk.content.partitions.swap.size = lib.mkForce "16384M";

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
