# Auto-generated by compose2nix.

{
  config,
  pkgs,
  lib,
  ...
}:
let
  version = "0.32.0"; # imgupdate https://github.com/karakeep-app/karakeep/releases/
in

{
  # Runtime
  sops.secrets."bookmarks/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };

  # Containers
  virtualisation.oci-containers.containers."bookmarks-chrome" = {
    image = "gcr.io/zenika-hub/alpine-chrome:123";
    environmentFiles = [ config.sops.secrets."bookmarks/env".path ];
    environment = {
      "HOARDER_VERSION" = "${version}";
    };
    cmd = [
      "--no-sandbox"
      "--disable-gpu"
      "--disable-dev-shm-usage"
      "--remote-debugging-address=0.0.0.0"
      "--remote-debugging-port=9222"
      "--hide-scrollbars"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=2"
      "--memory=1GB"
      "--network-alias=chrome"
      "--network=bookmarks_hoarder"
    ];
  };
  systemd.services."docker-bookmarks-chrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bookmarks_hoarder.service"
    ];
    requires = [
      "docker-network-bookmarks_hoarder.service"
    ];
    partOf = [
      "docker-compose-bookmarks-root.target"
    ];
    wantedBy = [
      "docker-compose-bookmarks-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bookmarks-meilisearch" = {
    image = "getmeili/meilisearch:v1.13.3";
    environmentFiles = [ config.sops.secrets."bookmarks/env".path ];
    environment = {
      "HOARDER_VERSION" = "${version}";
    };
    volumes = [
      "/data/docker/bookmarks/meilisearch:/meili_data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=meilisearch"
      "--network=bookmarks_hoarder"
    ];
  };
  systemd.services."docker-bookmarks-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bookmarks_hoarder.service"
    ];
    requires = [
      "docker-network-bookmarks_hoarder.service"
    ];
    partOf = [
      "docker-compose-bookmarks-root.target"
    ];
    wantedBy = [
      "docker-compose-bookmarks-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bookmarks_web" = {
    image = "ghcr.io/karakeep-app/karakeep:${version}";
    environmentFiles = [ config.sops.secrets."bookmarks/env".path ];
    environment = {
      "HOARDER_VERSION" = "${version}";
    };
    volumes = [
      "/data/docker/bookmarks/data:/data:rw"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.bookmarks-rtr.entrypoints" = "https";
      "traefik.http.routers.bookmarks-rtr.rule" = "Host(`bookmarks.ko0.net`)";
      "traefik.http.routers.bookmarks-rtr.service" = "bookmarks-svc";
      "traefik.http.routers.bookmarks-rtr.tls" = "true";
      "traefik.http.routers.bookmarks-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.bookmarks-svc.loadbalancer.server.port" = "3000";
    };
    log-driver = "journald";
    extraOptions = [
      "--cpus=1"
      "--memory=1GB"
      "--network-alias=web"
      "--network=chat"
      "--network=frontend"
      "--network=bookmarks_hoarder"
    ];
  };
  systemd.services."docker-bookmarks_web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bookmarks_hoarder.service"
    ];
    requires = [
      "docker-network-bookmarks_hoarder.service"
    ];
    partOf = [
      "docker-compose-bookmarks-root.target"
    ];
    wantedBy = [
      "docker-compose-bookmarks-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-bookmarks_hoarder" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bookmarks_hoarder";
    };
    script = ''
      docker network inspect bookmarks_hoarder || docker network create bookmarks_hoarder
    '';
    partOf = [ "docker-compose-bookmarks-root.target" ];
    wantedBy = [ "docker-compose-bookmarks-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bookmarks-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
