{
  pkgs,
  lib,
  config,
  ...
}:
let
  version = "v1.0.35"; # imgupdate https://github.com/Finsys/dockhand/releases
in

{
  imports = [ ./monitoring_network.nix ];

  # Containers
  virtualisation.oci-containers.containers."dockhand" = {
    image = "docker.io/fnsys/dockhand:${version}";
    volumes = [
      "/data/docker/dockhand/:/app/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.dockhand-rtr.entrypoints" = "https";
      "traefik.http.routers.dockhand-rtr.rule" = "Host(`operations.ko0.net`)";
      "traefik.http.routers.dockhand-rtr.service" = "dockhand-svc";
      "traefik.http.routers.dockhand-rtr.tls" = "true";
      "traefik.http.routers.dockhand-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.dockhand-svc.loadbalancer.server.port" = "3000";
    };
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.1"
      "--memory=500MB"
      "--network-alias=dockhand"
      "--network=dockhand_dockhand"
      "--network=frontend"
    ];
  };
  systemd.services."docker-dockhand" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dockhand_dockhand.service"
    ];
    requires = [
      "docker-network-dockhand_dockhand.service"
    ];
    partOf = [
      "docker-compose-dockhand-root.target"
    ];
    wantedBy = [
      "docker-compose-dockhand-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-dockhand-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

}
