{
  pkgs,
  lib,
  config,
  ...
}:

{

  sops.secrets."drawing/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;

    neededForUsers = false;
  };
  # Containers
  virtualisation.oci-containers.containers."excalidash-backend" = {
    image = "zimengxiong/excalidash-backend:latest";
    environmentFiles = [ config.sops.secrets."drawing/env".path ];

    environment = {
      "AUTH_MODE" = "local";
      "DATABASE_URL" = "file:/app/prisma/dev.db";
      "NODE_ENV" = "production";
      "PORT" = "8000";
      "TRUST_PROXY" = "false";
    };
    volumes = [
      "excalidash_backend-data:/app/prisma:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"node\", \"-e\", \"require('http').get('http://127.0.0.1:8000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--network-alias=backend"
      "--network=excalidash_excalidash-network"
    ];
  };
  systemd.services."docker-excalidash-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-excalidash_excalidash-network.service"
      "docker-volume-excalidash_backend-data.service"
    ];
    requires = [
      "docker-network-excalidash_excalidash-network.service"
      "docker-volume-excalidash_backend-data.service"
    ];
    partOf = [
      "docker-compose-excalidash-root.target"
    ];
    wantedBy = [
      "docker-compose-excalidash-root.target"
    ];
  };
  virtualisation.oci-containers.containers."excalidash-frontend" = {
    image = "zimengxiong/excalidash-frontend:latest";
    ports = [
      "127.0.0.1:6767:80/tcp"
    ];
    dependsOn = [
      "excalidash-backend"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"--quiet\", \"--tries=1\", \"--spider\", \"http://127.0.0.1:80\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--network-alias=frontend"
      "--network=excalidash_excalidash-network"
    ];
  };
  systemd.services."docker-excalidash-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-excalidash_excalidash-network.service"
    ];
    requires = [
      "docker-network-excalidash_excalidash-network.service"
    ];
    partOf = [
      "docker-compose-excalidash-root.target"
    ];
    wantedBy = [
      "docker-compose-excalidash-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-excalidash_excalidash-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f excalidash_excalidash-network";
    };
    script = ''
      docker network inspect excalidash_excalidash-network || docker network create excalidash_excalidash-network --driver=bridge
    '';
    partOf = [ "docker-compose-excalidash-root.target" ];
    wantedBy = [ "docker-compose-excalidash-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-excalidash_backend-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect excalidash_backend-data || docker volume create excalidash_backend-data
    '';
    partOf = [ "docker-compose-excalidash-root.target" ];
    wantedBy = [ "docker-compose-excalidash-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-excalidash-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
