{
  pkgs,
  lib,
  config,
  ...
}:

{

  sops.secrets."firefly/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };

  sops.secrets."firefly/env_db" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."firefly_iii_core" = {
    image = "fireflyiii/core:version-6.5.9";
    environmentFiles = [ config.sops.secrets."firefly/env".path ];
    volumes = [
      "/data/docker/firefly/upload:/var/www/html/storage/upload:rw"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.firefly-rtr.entrypoints" = "https";
      "traefik.http.routers.firefly-rtr.rule" = "Host(`budget.ko0.net`)";
      "traefik.http.routers.firefly-rtr.service" = "firefly-svc";
      "traefik.http.routers.firefly-rtr.tls" = "true";
      "traefik.http.routers.firefly-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.firefly-svc.loadbalancer.server.port" = "8080";
    };
    dependsOn = [
      "firefly_iii_db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=1"
      "--hostname=app"
      "--memory=524288000b"
      "--network-alias=app"
      "--network=firefly_budget"
      "--network=frontend"
    ];
  };
  systemd.services."docker-firefly_iii_core" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-firefly_budget.service"
    ];
    requires = [
      "docker-network-firefly_budget.service"
    ];
    partOf = [
      "docker-compose-firefly-root.target"
    ];
    wantedBy = [
      "docker-compose-firefly-root.target"
    ];
  };
  virtualisation.oci-containers.containers."firefly_iii_cron" = {
    image = "alpine";
    environmentFiles = [ config.sops.secrets."firefly/env".path ];
    cmd = [
      "sh"
      "-c"
      " apk add tzdata && ln -s /usr/share/zoneinfo/ /etc/localtime | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$STATIC_CRON_TOKEN;echo\" | crontab - && crond -f -L /dev/stdout"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.03"
      "--memory=500MB"
      "--network-alias=cron"
      "--network=firefly_budget"
    ];
  };
  systemd.services."docker-firefly_iii_cron" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-firefly_budget.service"
    ];
    requires = [
      "docker-network-firefly_budget.service"
    ];
    partOf = [
      "docker-compose-firefly-root.target"
    ];
    wantedBy = [
      "docker-compose-firefly-root.target"
    ];
  };
  virtualisation.oci-containers.containers."firefly_iii_db" = {
    image = "mariadb:lts";
    environmentFiles = [ config.sops.secrets."firefly/env_db".path ];
    volumes = [
      "/data/docker/firefly/db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.1"
      "--hostname=db"
      "--memory=1073741824b"
      "--network-alias=db"
      "--network=firefly_budget"
    ];
  };
  systemd.services."docker-firefly_iii_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-firefly_budget.service"
    ];
    requires = [
      "docker-network-firefly_budget.service"
    ];
    partOf = [
      "docker-compose-firefly-root.target"
    ];
    wantedBy = [
      "docker-compose-firefly-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-firefly_budget" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f firefly_budget";
    };
    script = ''
      docker network inspect firefly_budget || docker network create firefly_budget
    '';
    partOf = [ "docker-compose-firefly-root.target" ];
    wantedBy = [ "docker-compose-firefly-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-firefly-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
