{ pkgs, lib, ... }:

let
  version = "15.0.1"; # imgupdate https://forgejo.org/releases/
  url = "git.ko0.net";
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."forgejo" = {
    image = "codeberg.org/forgejo/forgejo:${version}";
    environment = {
      "USER_GID" = "100";
      "USER_UID" = "1442";
    };
    volumes = [
      "/data/docker/forgejo:/data:rw"
      "/etc/localtime:/etc/localtime:ro"
    ];
    ports = [
      "222:22/tcp"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.git-rtr.entrypoints" = "https";
      "traefik.http.routers.git-rtr.rule" = "Host(`${url}`)";
      "traefik.http.routers.git-rtr.service" = "git-svc";
      "traefik.http.routers.git-rtr.tls" = "true";
      "traefik.http.routers.git-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.git-svc.loadbalancer.server.port" = "3000";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=server"
      "--network=forgejo_forgejo"
      "--network=frontend"
    ];
  };
  systemd.services."docker-forgejo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-forgejo_forgejo.service"
    ];
    requires = [
      "docker-network-forgejo_forgejo.service"
    ];
    partOf = [
      "docker-compose-forgejo-root.target"
    ];
    wantedBy = [
      "docker-compose-forgejo-root.target"
    ];
  };
  virtualisation.oci-containers.containers."forgejo-dind" = {
    image = "docker:28.3.3-dind@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de";
    cmd = [
      "dockerd"
      "-H"
      "tcp://0.0.0.0:2375"
      "--tls=false"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dind"
      "--network=forgejo_forgejo"
      "--privileged"
    ];
  };
  systemd.services."docker-forgejo-dind" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-forgejo_forgejo.service"
    ];
    requires = [
      "docker-network-forgejo_forgejo.service"
    ];
    partOf = [
      "docker-compose-forgejo-root.target"
    ];
    wantedBy = [
      "docker-compose-forgejo-root.target"
    ];
  };
  virtualisation.oci-containers.containers."forgejo-runner" = {
    image = "code.forgejo.org/forgejo/runner:12.6.3";
    environment = {
      "DOCKER_HOST" = "tcp://dind:2375";
    };
    volumes = [
      "/data/docker/forgejo_runner:/data:rw"
    ];
    cmd = [
      "/bin/sh"
      "-c"
      "sleep 5; forgejo-runner daemon --config /data/config.yml"
    ];
    dependsOn = [
      "forgejo-dind"
    ];
    user = "1442:100";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=runner"
      "--network=forgejo_forgejo"
    ];
  };
  systemd.services."docker-forgejo-runner" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-forgejo_forgejo.service"
    ];
    requires = [
      "docker-network-forgejo_forgejo.service"
    ];
    partOf = [
      "docker-compose-forgejo-root.target"
    ];
    wantedBy = [
      "docker-compose-forgejo-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-forgejo_forgejo" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f forgejo_forgejo";
    };
    script = ''
      docker network inspect forgejo_forgejo || docker network create forgejo_forgejo
    '';
    partOf = [ "docker-compose-forgejo-root.target" ];
    wantedBy = [ "docker-compose-forgejo-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-forgejo-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
