{
  pkgs,
  lib,
  config,
  ...
}:
let
  version = "0.2.45"; # imgupdate https://github.com/Finsys/hawser/releases
in

{
  imports = [ ./monitoring_network.nix ];

  sops.secrets."hawser/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."hawser" = {
    image = "ghcr.io/finsys/hawser:${version}";
    environmentFiles = [ config.sops.secrets."hawser/env".path ];
    volumes = [
      "/data/docker/hawser/:/data/stacks:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    ports = [
      "2376:2376/tcp"
    ];
    extraOptions = [
      "--cpus=0.03"
      "--memory=50MB"
      "--network-alias=dockhand"
      "--network-alias=hawser"
      "--network=dockhand_dockhand"
    ];
  };
  systemd.services."docker-hawser" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dockhand_dockhand.service"
    ];
    requires = [
      "docker-network-dockhand_dockhand.service"
    ];
    partOf = [
      "docker-compose-hawser-root.target"
    ];
    wantedBy = [
      "docker-compose-hawser-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-hawser-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

}
