{
  pkgs,
  lib,
  config,
  ...
}:
let
  url = "photos.ko0.net";

  version = "v2.1.0";
  upload_dir = "/data/docker/immich/data";
  db_dir = "/data/docker/immich/postgress";
in
{

  sops.secrets."immich/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };

  sops.secrets."immich/db.env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."immich_server" = {
    image = "ghcr.io/immich-app/immich-server:${version}";
    environmentFiles = [ "/run/secrets-for-users/immich/env" ];

    environment = {
      "IMMICH_VERSION" = "${version}";
      "UPLOAD_LOCATION" = "${upload_dir}";
      "DB_DATA_LOCATION" = "${db_dir}";
    };
    volumes = [ "${upload_dir}:/data" ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.immich-rtr.entrypoints" = "https";
      "traefik.http.routers.immich-rtr.rule" = "Host(`${url}`)";
      "traefik.http.routers.immich-rtr.service" = "immich-svc";
      "traefik.http.routers.immich-rtr.tls" = "true";
      "traefik.http.routers.immich-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.immich-svc.loadbalancer.server.port" = "2283";
    };
    dependsOn = [
      "immich_postgres"
      "immich_redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=immich-server"
      "--network=frontend"
      "--network=immich"
    ];
  };

  virtualisation.oci-containers.containers."immich_machine_learning" = {
    image = "ghcr.io/immich-app/immich-machine-learning:${version}-cuda";
    volumes = [
      "immich_model-cache:/cache:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=immich-machine-learning"
      "--network=immich"
    ];
  };

  virtualisation.oci-containers.containers."immich_postgres" = {
    image = "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84";
    environmentFiles = [ "/run/secrets-for-users/immich/db.env" ];
    volumes = [
      "${db_dir}:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=database"
      "--network=immich"
      "--shm-size=134217728"
    ];
  };
  # Networks
  systemd.services."docker-network-immich" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f immich";
    };
    script = ''
      docker network inspect immich || docker network create immich
    '';
    partOf = [ "docker-compose-immich-root.target" ];
    wantedBy = [ "docker-compose-immich-root.target" ];
  };

  # Services
  systemd.services."docker-immich_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-immich.service"
    ];
    requires = [
      "docker-network-immich.service"
    ];
    partOf = [
      "docker-compose-immich-root.target"
    ];
    wantedBy = [
      "docker-compose-immich-root.target"
    ];
  };

  systemd.services."docker-immich_machine_learning" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;

    };
    after = [
      "docker-network-immich.service"
      "docker-volume-immich_model-cache.service"
    ];
    requires = [
      "docker-network-immich.service"
      "docker-volume-immich_model-cache.service"
    ];
    partOf = [
      "docker-compose-immich-root.target"
    ];
    wantedBy = [
      "docker-compose-immich-root.target"
    ];
  };

  systemd.services."docker-volume-immich_model-cache" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect immich_model-cache || docker volume create immich_model-cache
    '';
    partOf = [ "docker-compose-immich-root.target" ];
    wantedBy = [ "docker-compose-immich-root.target" ];
  };
  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-immich-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
