{
  pkgs,
  lib,
  config,
  ...
}:
{

  # Containers
  # Network
  systemd.services."docker-network-dockhand_dockhand" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f dockhand_dockhand";
    };
    script = ''
      docker network inspect dockhand_dockhand || docker network create dockhand_dockhand
    '';
    partOf = [ "docker-compose-monitoring-network.target" ];
    wantedBy = [ "docker-compose-monitoring-network.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-monitoring-network" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

}
