{
  lib,
  config,
  pkgs,
  ...
}:
let
  version = "0.63.2";
in
{
  sops.secrets."music/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;

    neededForUsers = true;
  };
  sops.secrets."music/backup_dest" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    owner = config.users.users.eragon.name;
    mode = "0440";
  };

  # Containers
  virtualisation.oci-containers.containers."music-navidrome" = {
    image = "docker.io/deluan/navidrome:${version}"; # imgupdate https://github.com/navidrome/navidrome/releases

    environmentFiles = [ "/run/secrets-for-users/music/env" ];

    environment = {
      "ND_LISTENBRAINZ_BASEURL" = "http://music-maloja:42010/apis/listenbrainz/1/";
    };

    volumes = [
      "/data/docker/navidrome/:/data:rw"
      "/data/docker/downloader/storage/media/music/:/music:ro"
      "/data/docker/downloader/storage/media/music/Playlists:/music/Playlists:rw"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.navidrome-rtr.entrypoints" = "https";
      "traefik.http.routers.navidrome-rtr.rule" = "Host(`music.ko0.net`)";
      "traefik.http.routers.navidrome-rtr.service" = "navidrome-svc";
      "traefik.http.routers.navidrome-rtr.tls" = "true";
      "traefik.http.routers.navidrome-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.navidrome-svc.loadbalancer.server.port" = "4533";
    };
    user = "1442:100";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=navidrome"
      "--network=frontend"
    ];
  };

  virtualisation.oci-containers.containers."music-maloja" = {
    image = "docker.io/krateng/maloja:3.2.4";

    environment = {
      "ND_LISTENBRAINZ_BASEURL" = "http://music-maloja-1:42010/apis/listenbrainz/1/";
      "MALOJA_DATA_DIRECTORY" = "/mljdata";
      "MALOJA_SKIP_SETUP" = "yes";
    };

    volumes = [ "/data/docker/lastfm:/mljdata:rw" ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.maloja-rtr.entrypoints" = "https";
      "traefik.http.routers.maloja-rtr.rule" = "Host(`lastfm.ko0.net`)";
      "traefik.http.routers.maloja-rtr.service" = "maloja-svc";
      "traefik.http.routers.maloja-rtr.tls" = "true";
      "traefik.http.routers.maloja-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.maloja-svc.loadbalancer.server.port" = "42010";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=maloja"
      "--network=frontend"
    ];
  };

  systemd.services."docker-music-navidrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-music-root.target" ];
    wantedBy = [ "docker-compose-music-root.target" ];
  };

  systemd.services."docker-music-maloja" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-music-root.target" ];
    wantedBy = [ "docker-compose-music-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-music-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  # Crontab sync
  systemd.services.music-backup-script = {
    description = "Daily remote backup for music.";
    serviceConfig = {
      Type = "oneshot";
      User = config.users.users.eragon.name;
      ExecStart = ''
        ${pkgs.rsync}/bin/rsync -avh --bwlimit=1.5m --progress -e 'ssh -i ${config.users.users.eragon.home}/.ssh/id_ed25519 -p 23' /data/docker/downloader/storage/media/music  "$(cat ${
          config.sops.secrets."music/backup_dest".path
        })"
      '';
    };
  };

  systemd.timers.music-backup-script = {
    description = "Run the sync script daily at 2:30AM";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "02:30";
      Persistent = true; # Run immediately if missed (e.g., after downtime)
    };
  };
}
