{
  pkgs,
  config,
  lib,
  ...
}:
{

  sops.secrets."newt/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
  };

  # Containers
  virtualisation.oci-containers.containers."newt" = {
    image = "fosrl/newt:latest";
    environmentFiles = [ config.sops.secrets."newt/env".path ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=newt"
      "--network=frontend"
    ];
  };
  systemd.services."docker-newt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container newt generated by compose2nix.";
    partOf = [
      "docker-compose-newt-root.target"
    ];
    wantedBy = [
      "docker-compose-newt-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-newt-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
