{ config, lib, ... }:
let
  version = "v1.54.0";
in
{

  sops.secrets."portal/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."portal-homarr" = {
    image = "ghcr.io/homarr-labs/homarr:${version}";
    environmentFiles = [ config.sops.secrets."portal/env".path ];
    environment = {
      "BASE_URL" = "portal.ko0.net";
    };
    volumes = [
      "/data/docker/homarr:/appdata:rw"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.portal-rtr.entrypoints" = "https";
      "traefik.http.routers.portal-rtr.rule" = "Host(`portal.ko0.net`)";
      "traefik.http.routers.portal-rtr.service" = "portal-svc";
      "traefik.http.routers.portal-rtr.tls" = "true";
      "traefik.http.routers.portal-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.portal-svc.loadbalancer.server.port" = "7575";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homarr"
      "--network=frontend"
    ];
  };
  systemd.services."docker-portal-homarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-portal-root.target"
    ];
    wantedBy = [
      "docker-compose-portal-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-portal-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
