{
  lib,
  config,
  ...
}:

let
  version = "0.32.0"; # imgupdate https://github.com/Finsys/hawser/releases
  gid = 100;
  uid = 1442;
  git_branch = "port/docker-compose-migration";
in
{
  sops.secrets."releases/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };
  # Containers
  virtualisation.oci-containers.containers."releases-argus" = {
    image = "releaseargus/argus:${version}";
    environmentFiles = [ config.sops.secrets."releases/env".path ];
    environment = {
      "ARGUS_GID" = toString gid;
      "ARGUS_UID" = toString uid;
      "GIT_BRANCH" = git_branch;
    };
    volumes = [
      "/data/docker/releases/db/:/app/data"
      "/etc/releases/config.yml:/app/config.yml:ro"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.releases-rtr.entrypoints" = "https";
      "traefik.http.routers.releases-rtr.rule" = "Host(`releases.ko0.net`)";
      "traefik.http.routers.releases-rtr.service" = "releases-svc";
      "traefik.http.routers.releases-rtr.tls" = "true";
      "traefik.http.routers.releases-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.releases-svc.loadbalancer.server.port" = "8080";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=/healthcheck http://localhost:8080/api/v1/healthcheck"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=10s"
      "--health-timeout=10s"
      "--network-alias=argus"
      "--network=frontend"
    ];
  };
  systemd.services."docker-releases-argus" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-releases-root.target"
    ];
    wantedBy = [
      "docker-compose-releases-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-releases-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  environment.etc."releases/config.yml" = {
    gid = gid;
    uid = uid;
    source = ./config/releases.yml;
  };

}
