# Auto-generated by compose2nix.

{
  config,
  pkgs,
  lib,
  ...
}:
let
  version = "v2.3.0"; # imgupdate https://git.deuxfleurs.fr/Deuxfleurs/garage/tags
in
{
  # Containers
  virtualisation.oci-containers.containers."garaged" = {
    image = "dxflrs/garage:${version}";
    volumes = [
      "/data/s3/data:/var/lib/garage/data:rw"
      "/data/s3/garage.toml:/etc/garage.toml:rw"
      "/data/s3/meta:/var/lib/garage/meta:rw"
    ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.demo-rtr.entrypoints" = "https";
      "traefik.http.routers.demo-rtr.rule" = "Host(`demo.ko0.net`)";
      "traefik.http.routers.demo-rtr.service" = "demo-svc";
      "traefik.http.routers.demo-rtr.tls" = "true";
      "traefik.http.routers.demo-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.routers.s3-store-rtr.entrypoints" = "https";
      "traefik.http.routers.s3-store-rtr.rule" = "Host(`storage.ko0.net`)";
      "traefik.http.routers.s3-store-rtr.service" = "s3-store-svc";
      "traefik.http.routers.s3-store-rtr.tls" = "true";
      "traefik.http.routers.s3-store-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.demo-svc.loadbalancer.server.port" = "3902";
      "traefik.http.services.s3-store-svc.loadbalancer.server.port" = "3900";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=garage"
      "--network=frontend"
    ];
  };
  systemd.services."docker-garaged" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-s3-root.target"
    ];
    wantedBy = [
      "docker-compose-s3-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-s3-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
