# Auto-generated by compose2nix.

{
  config,
  pkgs,
  lib,
  ...
}:
let
  version = "2"; # imgupdate https://docs.requarks.io/releases
in
{

  sops.secrets."wiki/env" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };

  sops.secrets."wiki/env_db" = {
    sopsFile = ../../../../${config.networking.hostName}/secrets.yml;
    neededForUsers = true;
  };

  # Containers
  virtualisation.oci-containers.containers."wiki-wikijs" = {
    image = "ghcr.io/requarks/wiki:${version}";
    environmentFiles = [ config.sops.secrets."wiki/env".path ];
    labels = {
      "traefik.docker.network" = "frontend";
      "traefik.enable" = "true";
      "traefik.http.routers.notes-rtr.entrypoints" = "https";
      "traefik.http.routers.notes-rtr.rule" = "Host(`wiki.ko0.net`)";
      "traefik.http.routers.notes-rtr.service" = "notes-svc";
      "traefik.http.routers.notes-rtr.tls" = "true";
      "traefik.http.routers.notes-rtr.tls.certresolver" = "cloudflare";
      "traefik.http.services.notes-svc.loadbalancer.server.port" = "3000";
    };
    dependsOn = [
      "wikijs_db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wikijs"
      "--network=frontend"
      "--network=wiki_wikijs"
    ];
  };
  systemd.services."docker-wiki-wikijs" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wiki_wikijs.service"
    ];
    requires = [
      "docker-network-wiki_wikijs.service"
    ];
    partOf = [
      "docker-compose-wiki-root.target"
    ];
    wantedBy = [
      "docker-compose-wiki-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wikijs_db" = {
    image = "postgres:15-alpine";
    environmentFiles = [ config.sops.secrets."wiki/env_db".path ];
    volumes = [
      "/data/docker/wikijs/db/:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=frontend"
    ];
  };
  systemd.services."docker-wikijs_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-wiki-root.target"
    ];
    wantedBy = [
      "docker-compose-wiki-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wiki_wikijs" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wiki_wikijs";
    };
    script = ''
      docker network inspect wiki_wikijs || docker network create wiki_wikijs
    '';
    partOf = [ "docker-compose-wiki-root.target" ];
    wantedBy = [ "docker-compose-wiki-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wiki-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
